sudo: required
services:
  - docker
  
before_install:
  - docker build -t hark3003/docker-react -f Dockerfile.dev .

script:
  - docker run hark3003/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ind-east"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ind-east-26352217"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"


